services:
  - type: web
    name: intelligeo-app
    env: static
    branch: main
    buildCommand: npm install && npm run build && if [ -d dist ] && [ ! -d build ]; then cp -R dist build; fi
    staticPublishPath: build
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 22

autoDeploy: true
